# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

target 'MyTaxis' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyTaxis

  target 'MyTaxis-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTaxisTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
