# Created by react-native-pod
target 'MyTaxis' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  # Add new pods below this line
  target 'MyTaxisTests' do
    inherit! :search_paths
    # Pods for testing
    # Add new pods below this line
  end
end
target 'MyTaxis-tvOS' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  target 'MyTaxis-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end